### ISSUE TITLE
Enable jp translation fully in CI

### ISSUE THREAD

**Issue by solana-grimes** [solana-labs/whitepaper#45] opened 2018-06-08 06:32 UTC
#44 did most of the work to build the jp translation automatically.  Uncomment https://github.com/solana-labs/whitepaper/blob/92c76b901bc3aa31ac73450094b5a71c6298dbb6/ci/build.sh#L31-L37 and figure out why it doesn't build in the CI environment.  Perhaps we're missing some fonts/etc?

@jangsa - if you have any ideas what might be going wrong please chime in, thanks!

**Comment by jangsa** [comment] 2018-06-08 11:47
Hi. Let me look into this problem in Linux environment w/o Japanese installation initially.
One thing I'd like you to try: use "lualatex" instead of "luatex".

**Comment by jangsa** [comment] 2018-06-09 01:48
This problem looks like due to absence of Japanese character sets (or not recognized...as you guessed!).

It's so hard to reproduce Mac w/o Japanese at the moment, so I feel very sorry for taking up your time but if possible please try the following commands (I'm assuming you're using MacTeX or TeX Live):

$ sudo tlmgr update --self --all

$ sudo cjk-gs-integrate --link-texmf --cleanup

$ sudo cjk-gs-integrate-macos --link-texmf

(if yourMacOS == "High Sierra")
$ sudo kanji-config-updmap-sys --jis2004 hiragino-highsierra-pron

(else if yourMacOS == "Sierra" || yourMacOS == "El Capitan")
$ sudo kanji-config-updmap-sys --jis2004 hiragino-elcapitan-pron

(else update your Mac and try one of above accordingly!)

---

If the above fails, you might need to modify language config of your Mac.

Please follow below link:
https://support.apple.com/kb/PH24342?locale=en_US&viewlocale=en_US
https://support.apple.com/kb/ph16940?locale=en_US

Still not succeed, I'll look into it more deeply.
If succeed, I'll update README.md accordingly. :)

**Comment by mvines** [comment] 2018-07-01 15:01
Yep this is fixed now, thanks for pointing this out @jangsa

**Closed by mvines** 2018-07-01 15:01 UTC
